# Generated by Django 5.0 on 2024-01-06 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_alter_player_player_shirt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcode',
            name='team_code_expiry_date',
            field=models.DateField(default=datetime.date(2024, 1, 13), help_text='Default is 7 days from now'),
        ),
    ]
