# Generated by Django 5.0 on 2024-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0009_alter_genderleaguetype_options_team_team_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, default='images/person-placeholder.png', upload_to='player_images/'),
        ),
    ]
