# Generated by Django 5.0 on 2023-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0005_alter_team_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_shirt_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(upload_to='team_logos/'),
        ),
    ]
