# Generated by Django 5.0 on 2024-01-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0008_genderleaguetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genderleaguetype',
            options={'verbose_name': 'Volleyball Gender League Type'},
        ),
        migrations.AddField(
            model_name='team',
            name='team_gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=20),
        ),
        migrations.AlterField(
            model_name='genderleaguetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='langing_pages_images/'),
        ),
    ]
