# Generated by Django 5.0 on 2024-01-09 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0009_alter_genderleaguetype_options_team_team_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcode',
            name='team_code_expiry_date',
            field=models.DateField(default=datetime.date(2024, 1, 16), help_text='Default is 7 days from now'),
        ),
    ]
