# Generated by Django 5.0 on 2024-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_player_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderleaguetype',
            name='image',
            field=models.ImageField(upload_to='langing_pages_images/'),
        ),
    ]
