# Generated by Django 4.1.1 on 2023-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='route_name',
            field=models.CharField(default='home', help_text='this route name given url. Leave as home. e.g for basketball the route name is schedule', max_length=225),
        ),
    ]
