# Generated by Django 4.1.1 on 2023-09-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_landingpage_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='route_name',
            field=models.CharField(default='home', help_text='this route name given url.py. Leave default home if  no route yet given.E.g for basketball the route name is schedule', max_length=225),
        ),
    ]
