# Generated by Django 5.0 on 2024-01-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_landingpage_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderLeagueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=20)),
            ],
        ),
    ]
