# Generated by Django 5.0 on 2024-01-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_genderleaguetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genderleaguetype',
            unique_together={('gender',)},
        ),
    ]
