# Generated by Django 5.0 on 2024-01-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_genderleaguetype_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenderLeagueType',
        ),
    ]
