# Generated by Django 5.0 on 2024-01-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_genderleaguetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='langing_pages_images/'),
        ),
    ]
